### ISSUE TITLE
AttributeError: module 'curies' has no attribute 'Record'

### ISSUE THREAD

**Issue by hrshdhgd** [biopragmatics/bioregistry#634]
@justaddcoffee, @cmungall , @caufieldjh  and I were working on `oaklib` and after updating to the latest version of bioregistry (v0.5.36) , a process throws the following error stack-trace: 

```
(oakx-grape-env) poetry run runoak -i grape:sqlite:obo:hp viz -p i,p HP:0002550 MP:0003761 -o 415139071.png --no-view
Traceback (most recent call last):
  File "../runoak", line 5, in <module>
    from oaklib.cli import main
  File "../oaklib/__init__.py", line 9, in <module>
    from oaklib.selector import get_implementation_from_shorthand  # noqa:F401
  File "../oaklib/selector.py", line 8, in <module>
    from oaklib.implementations import GildaImplementation
  File "..s/oaklib/implementations/__init__.py", line 12, in <module>
    from oaklib.implementations.ontobee.ontobee_implementation import OntobeeImplementation
  File "../oaklib/implementations/ontobee/ontobee_implementation.py", line 4, in <module>
    from oaklib.implementations.sparql.abstract_sparql_implementation import (
  File "../oaklib/implementations/sparql/abstract_sparql_implementation.py", line 9, in <module>
    import kgcl_rdflib.kgcl_diff as kgcl_diff
  File "../site-packages/kgcl_rdflib/kgcl_diff.py", line 16, in <module>
    from kgcl_rdflib.diff.pretty_print_kgcl import render_instances
  File "../site-packages/kgcl_rdflib/diff/pretty_print_kgcl.py", line 9, in <module>
    from kgcl_schema.grammar.parser import parse_statement
  File "../kgcl_schema/grammar/parser.py", line 9, in <module>
    from bioregistry import parse_iri, get_preferred_prefix, curie_to_str
  File "../site-packages/bioregistry/__init__.py", line 5, in <module>
    from .collection_api import get_collection, get_context  # noqa:F401
  File "../site-packages/bioregistry/collection_api.py", line 7, in <module>
    from .resource_manager import manager
  File "../site-packages/bioregistry/resource_manager.py", line 86, in <module>
    class Manager:
  File "../site-packages/bioregistry/resource_manager.py", line 428, in Manager
    ) -> List[curies.Record]:
AttributeError: module 'curies' has no attribute 'Record'
```

Rolling it back to v0.5.34 made the error go away. just thought of documenting it here.

**Comment by cthoyt** [comment]
Also I think the way you've copied the Bioregistry version is very wrong, 0.1.36 is from like 2 years ago

**Comment by hrshdhgd** [comment]
Oops... fixed it!

**Comment by cthoyt** [comment]
I think that all of the solutions will come from various downstream version pin fixes, but please feel free to comment if there are some other concerns and we can re-open this
