### ISSUE TITLE
bioregistry cannot be imported when installed in system directories

### ISSUE THREAD

**Issue by gouttegd** [biopragmatics/bioregistry#705]
When `bioregistry` is installed in a system-wide directory (e.g. `/usr/lib/python3.Y/site-packages`), trying to load it yield the following error:

```sh
$ python3 -m bioregistry
Traceback (most recent call last):
  File "/usr/lib64/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib64/python3.9/exports/benchmarks/uri_parsing'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib64/python3.9/exports/benchmarks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib64/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib64/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/lib64/python3.9/site-packages/bioregistry/__init__.py", line 5, in <module>
    from .collection_api import get_collection, get_context  # noqa:F401
  File "/usr/lib64/python3.9/site-packages/bioregistry/collection_api.py", line 7, in <module>
    from .resource_manager import manager
  File "/usr/lib64/python3.9/site-packages/bioregistry/resource_manager.py", line 27, in <module>
    from .constants import (
  File "/usr/lib64/python3.9/site-packages/bioregistry/constants.py", line 86, in <module>
    URI_PARSING.mkdir(exist_ok=True, parents=True)
  File "/usr/lib64/python3.9/pathlib.py", line 1327, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib64/python3.9/pathlib.py", line 1327, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib64/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/usr/lib64/python3.9/exports'
```

This is because the `constants.py` module unconditionally attempts to create directories at locations that depend on the location of the module itself:

```python
HERE = pathlib.Path(os.path.abspath(os.path.dirname(__file__)))
[...]
ROOT = HERE.parent.parent.resolve()
[...]
EXPORT_DIRECTORY = ROOT.joinpath("exports")
[...]
BENCHMARKS = EXPORT_DIRECTORY.joinpath("benchmarks")

URI_PARSING = BENCHMARKS.joinpath("uri_parsing")
URI_PARSING.mkdir(exist_ok=True, parents=True)
```

Obviously, there is an assumption here that `bioregistry` will either only be used by an account with root privileges or that it will only be installed by users in a writable Python tree (e.g. with `pip install --user` or inside a Virtualenv-style environment).

If the package has to write some data somewhere as part of its normal behaviour, it should not do so in its installation directory, or at the very least it should detect when its installation is not writable and fallback to a per-user writable directory.

**Comment by bgyori** [comment]
Thanks @gouttegd, I agree with your assessment that these additional folders should not be attempted to be created this way for non-development instances of Bioregistry.

**Comment by cthoyt** [comment]
Thanks @gouttegd and @bgyori, will fix this asap
